# -*- encoding : utf-8 -*-
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))

Given /^(?:|I )am on (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )go to (.+)$/ do |page_name|
  visit path_to(page_name)
end

Then /^(?:|I )should be on (.+)$/ do |page_name|
  current_path = URI.parse(current_url).path
  # puts current_path
  # puts path_to(page_name)
  if current_path.respond_to? :should
    current_path.should == path_to(page_name)
  else
    assert_equal path_to(page_name), current_path
  end
end

Then /^show me the page$/ do
  save_and_open_page
end

When(/^I press the button "(.*?)"$/) do |button|
  click_button button
end

When(/^I follow the link "(.*?)"$/) do |link|
  click_link link
end

Then(/^I should see the content "(.*?)"$/) do |content|
  should have_content content
end

Then(/^I should not see the content "(.*?)"$/) do |content|
  should_not have_content content
end

When(/^I reload the page$/) do
  visit current_path
end

When(/^I fill in "(.*?)" with "(.*?)"$/) do |selector, value|
  fill_in(selector, with: value)
end
